### ISSUE TITLE
Deploy.js Is Not Built For Cross-Platform Usability

### ISSUE THREAD

**Issue by zlavoie** [aws-samples/amazon-chime-live-events#4]
amazon-chime-live-events\src\backend\serverless\deploy.js is not built for cross-platform usability. Currently this does not support windows machines. NPM Cross-spawn an be used to offer compatibility, but sections of the script such as:
```
spawnOrFail('find', ['.', '-type', 'f', '-exec', 'touch', '{}', ';'], {
  cwd: path.resolve('src/node_modules')
});
```
and
```
spawnOrFail('npm', ['run', 'release'], {
  cwd: path.resolve('../../../')
});
```
will continue to fail.

**Comment by devalevenkatesh** [comment]
Yes, it may not be cross-platform since this demo was built and tested on Cloud9, macOS, linux but not on windows. We would appreciate if we get some help on making it compatible for Windows OS and make any minor adjusts to the deploy script.

As of now, we are keeping this issue open for developers to know about it and get some help.

Thanks.
