### ISSUE TITLE
Issue to running demo of live event amazon chime

### ISSUE THREAD

**Issue by mobcoder-deepanshu** [aws-samples/amazon-chime-live-events#49]
Actually, I run a demo of live event through chime sdk
here is the link from which i refer to run demo - https://aws.amazon.com/blogs/opensource/how-to-deploy-a-live-events-solution-built-with-the-amazon-chime-sdk/ 
So I stuck in the middle run and didn't run the demo on my local system so can you explain me the steps so i can easily run the demo.
And Readme is not properly understandable, there is no steps of how to run this demo locally .
Please help for the same.

Thanks

**Comment by michhyun1** [comment]
hi @mobcoder-deepanshu, thank you for your interest in the live events demo. We are currently working on improving this README. For now, I suggest trying to deploy a server-less demo to try this out. You can run each app locally, but there are some cloud backend resources you'll need to deploy for the demo to work correctly. 

Please note that following the steps below will incur some AWS charges. 

For now, I'll just post a simple process:
1. Run the deploy script - you can find that [here](https://github.com/aws-samples/amazon-chime-live-events/tree/master/src/backend/serverless). Before you do, make sure you have all of the prerequisites mentioned in the README. Also, make sure you use a unique stack and bucket name - do not use the default. If this fails, try using a different bucket and stack name. 

2.  Next, you want to generate your custom resources. You can check how to do that [here](https://github.com/aws-samples/amazon-chime-live-events#creating-live-event-resources). This step will give you the URLs that you can visit to join the live event as a Moderator, Attendee, and Talent. (The broadcast url is not meant to be joined by a person - our broadcast lambda will be using that url in step 4)

3.  Next, go to the CloudFormation stack that was generated in Step 1. There should be three stacks generated - you want the main cloudformation stack - that does not have the word '-broadcast' appended to it. (Not the nested stack either) Go to the 'outputs' tab and note the MediaLiveChannel value. Navigate to AWS MediaLive in your AWS console, and find the MediaLive channel that corresponds to the MediaLiveChannel Id that is indicated in your CloudFormation outputs. Start the channel by pressing the 'Start' button.

4. Next, you should start the broadcast lambda by running a test event against the broadcast lambda that was created when you deployed in step 1. You can find an example of a test event [here](https://github.com/aws-samples/amazon-chime-live-events/blob/master/transcoding/README.md#options-to-startstop-transcoding). Navigate back to the `CustomerImportS3Bucket` S3 bucket - the arn to the s3 is specified in the main cloudformation stack. There should be generated json files for the Moderator, Attendees, Talents and Broadcaster. For the `meeting URL` - open the generated Broadcast json and use the url inside this json as the value. For the RTMP endpoint - use the `MediaLivePrimaryEndpoint` value from your CloudFormation stack outputs.

5. Navigate back to the `CustomerImportS3Bucket` S3 bucket - the arn to the s3 is specified in the main cloudformation stack. You can join the live event by using the URLs inside the newly generated Attendee/Talent/Moderator json files. When you join as a Moderator, you should see that the `Broadcaster` on the roster, indicating that the transcoding lambda is working to record the live event and broadcast to to the RTMP endpoint, so that the attendees can see the live event stream.

Please let us know if you have any questions. Thanks

**Comment by mobcoder-deepanshu** [comment]
Hi @michhyun1 
Thanks for the helpful response and describe everything very well.But That's not enough for me to run this demo.
So,I didn't understand the cloud formation and from where i found stack name.
Can we connect through zoom or google meet or skype to run this demo on my local machine because it's urgent for me.

Best Regards 
Deepanshu Garg

**Comment by michhyun1** [comment]
@mobcoder-deepanshu you can find the stack name in the aws cloudformation console - there are multiple tabs that show you the created resources and outputs.

**Comment by michhyun1** [comment]
Apologies, we won't be able to join any call with you directly. If you need additional please come via the support channels. You can find more information [here](https://github.com/aws/amazon-chime-sdk-js#troubleshooting-and-support).

**Comment by mobcoder-deepanshu** [comment]
@michhyun1 ok no problem.
I have some doubt can you clear that-

1.Why we use stack name or cloud formation in this?
2.Do we have any other option without using stack name ?
3.In this demo what is the use of stack name ?

Because i didn't understand cloudformation or stack after i read thorughly about this but not satisfied 
Can you explain Please!

Thanks

**Comment by michhyun1** [comment]
@mobcoder-deepanshu You can refer to the [cloudformation documentation](https://aws.amazon.com/cloudformation/). Cloudformation allows us to deploy AWS cloud resources that are required to run this demo serverlessly. This includes lambda functions, EC2 instances, and much more. You can see the resources generated by going to the cloudformation stack that you created as part of the deploy script. Inside the stack will contain all of the cloud resources that were generated. 

The cloudformation stack also will output [important endpoints](https://github.com/aws-samples/amazon-chime-live-events/tree/master/src/backend/serverless#outputs) that you'll need to start the live event. 

For more information on running the deploy script and what it does, you can refer to the [README](https://github.com/aws-samples/amazon-chime-live-events/tree/master/src/backend/serverless#what-exactly-will-running-deployjs-do).

**Comment by mobcoder-deepanshu** [comment]
Hi @michhyun1,

I have an question regrading cloud formation that why we use cloud formation in this demo?
Can we have any alternative or any other option without using this service?

Please can you explain me regarding this.

Thanks

**Comment by michhyun1** [comment]
@mobcoder-deepanshu This is a demo to show how to build a live events solution. CloudFormation is used by most of our demos, the alternative is you can configure and create each of the resources in the cloud manually - however, this demo does not aim to show you how to do this. You may want to refer to the CloudFormation documentation to learn more. If you have a specific question about this demo, feel free to ask. Otherwise, I'll close out this issue. Feel free to re-open if you have specific issues with this demo.
