### ISSUE TITLE
why we use cloud formation in this demo?

### ISSUE THREAD

**Issue by mobcoder-deepanshu** [aws-samples/amazon-chime-live-events#53]
Hello

I have an query that why we use cloud formation in this demo and there is any other alternative without using cloud formation ?

Do we have another demo without cloud formation?

Thanks

**Comment by michhyun1** [comment]
@mobcoder-deepanshu You may try using [CDK](https://aws.amazon.com/cdk/) if you'd prefer, but under the hood, CDK also uses CloudFormation. AWS CloudFormation allows you to create your AWS Cloud resources programmatically instead of manually through the AWS console. 

If you'd like to create the resources manually, that is an option, but we prefer to use cloudformation in our demos so that it is easy to generate the backend resources required by the demo. Closing this issue now, please reopen if you have any questions related to this demo. Please direct any questions regarding cloudformation to the [cloudformation documentation](https://aws.amazon.com/cloudformation/).
